### ISSUE TITLE
Docs mention `t.String(regex=)` which doesn't work any more

### ISSUE THREAD

**Issue by tailhook** [Deepwalker/trafaret#39]
In particular in the [Introducing trafaret](https://trafaret.readthedocs.io/en/latest/intro.html#string-email-url) section.

**Comment by mariocesar** [comment]
The main docs are built for the branch `master` the branch `version2` is the one that has the regex argument removed. Checking on the String class -> https://github.com/Deepwalker/trafaret/blob/version2/trafaret/base.py#L593-L620 there is no more mention to regex.

The problem here is that the docs are not versioned, they must have versions, and also versions in 1.0 not have backwards incompatibility. The current master version has the regexp argument removed.

So will be nice if the docs are versioned, and the branches also.

**Comment by nimnull** [comment]
@Deepwalker consider resolving this issue due to  PR #41 merge
